- alias: "Notify when washing machine complete"
  trigger:
    platform: numeric_state
    entity_id: sensor.washing_machine_watts
    above: 1.3
    below: 1.4
  action:
    service: notify.washing_machine
    data_template:
      title: "Washing machine complete"
      message: "The washing machine has finished. You should remove the clothes."
    #service: tts.google_say
    #entity_id: media_player.kitchen_speaker
    #message: 'The laundry is complete.'
