title: Boobie Bungalow
views:
  - title: Lights
#    panel: false
    cards: 
      - type: entities
        title: Office
        entities:
          - light.desk
          - light.office_fan_light
      - type: entities
        title: Living Room
        entities: 
          - light.living_room_light
#Bedroom Light Group
      - type: entities
        title: Bedroom
        entities: 
          - light.bedroom_fan
          - light.nightstand_left
          - light.nightstand_right
          - light.nightstand_lights
          - light.hallway_light
#Spare Room Light Group
      - type: entities
        title: Spare Room
        entities: 
          - light.spare_room
#Front Room Light Group
      - type: entities
        title: Front Room
        entities: 
          - light.front_room_lamp
          - light.front_lamp
          - light.foyer_light
          - light.dining_room_light
#Kitchen Light Group
      - type: entities
        title: Kitchen
        entities: 
          - light.kitchen_left
          - light.kitchen_right
          - light.kitchen 
#Thermostat Card
      - type: thermostat
        entity: climate.home